os: linux
language: node_js
node_js:
  - "16"

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2
    - ACCOUNT_ID=566318860935
    - COUNTRY=au
    - STAGE=dev
    - ROOTDOMAIN=truuth.id

cache:
  npm: false

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - npm install -g serverless
  - travis_retry npm ci
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -q awscliv2.zip
  - sudo ./aws/install
  - chmod +x ./assume_role.sh

jobs:
  include:
    - stage: Test
      if: type = pull_request
      script:
      - npm test

    - stage: Deploy
      if: (branch IN (master) AND type != pull_request) OR (branch NOT IN (master) AND type NOT IN (push, pull_request))
      script:
      - bash assume_role.sh arn:aws:iam::${ACCOUNT_ID}:role/TravisCrossAccount ${STAGE}
      - serverless deploy --aws-profile ${STAGE} --stage ${STAGE} --region ${AWS_DEFAULT_REGION} --param="account=${ACCOUNT_ID}"  --param="country=${COUNTRY}" --param="rootDomain=${ROOTDOMAIN}" --param="version=${TRAVIS_COMMIT}"
